name: Build APK from ZIP

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip project
        run: |
          unzip wifi-focus.zip
          cp -r wifi-focus/* . || true
          cp -r wifi-focus/.* . || true

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Change permissions
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: app/build/outputs/apk/debug/*.apk
